-- MySQL Script generated by MySQL Workbench
-- sex 06 dez 2019 22:36:33 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema marioKart
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `marioKart` ;

-- -----------------------------------------------------
-- Schema marioKart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `marioKart` DEFAULT CHARACTER SET utf8 ;
USE `marioKart` ;

-- -----------------------------------------------------
-- Table `marioKart`.`Personagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marioKart`.`Personagem` ;

CREATE TABLE IF NOT EXISTS `marioKart`.`Personagem` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `velocidade` DECIMAL NOT NULL,
  `aceleracao` DECIMAL NOT NULL,
  `peso` DECIMAL NOT NULL,
  `manobra` DECIMAL NOT NULL,
  `tracao` DECIMAL NOT NULL,
  `turbo` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marioKart`.`Jogador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marioKart`.`Jogador` ;

CREATE TABLE IF NOT EXISTS `marioKart`.`Jogador` (
  `id` INT NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `idPersonagem` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Jogador_Personagem_idx` (`idPersonagem` ASC),
  CONSTRAINT `fk_Jogador_Personagem`
    FOREIGN KEY (`idPersonagem`)
    REFERENCES `marioKart`.`Personagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `marioKart`.`Personagem`
-- -----------------------------------------------------
START TRANSACTION;
USE `marioKart`;
INSERT INTO `marioKart`.`Personagem` (`id`, `nome`, `velocidade`, `aceleracao`, `peso`, `manobra`, `tracao`, `turbo`) VALUES (1, 'Mario', 89, 77, 85, 69, 60, 90);
INSERT INTO `marioKart`.`Personagem` (`id`, `nome`, `velocidade`, `aceleracao`, `peso`, `manobra`, `tracao`, `turbo`) VALUES (2, 'Luigi', 77, 81, 70, 75, 70, 97);
INSERT INTO `marioKart`.`Personagem` (`id`, `nome`, `velocidade`, `aceleracao`, `peso`, `manobra`, `tracao`, `turbo`) VALUES (3, 'Princesa Peach', 70, 90, 60, 87, 71, 92);
INSERT INTO `marioKart`.`Personagem` (`id`, `nome`, `velocidade`, `aceleracao`, `peso`, `manobra`, `tracao`, `turbo`) VALUES (4, 'Yoshi', 83, 75, 50, 98, 82, 85);
INSERT INTO `marioKart`.`Personagem` (`id`, `nome`, `velocidade`, `aceleracao`, `peso`, `manobra`, `tracao`, `turbo`) VALUES (5, 'Toad', 85, 70, 65, 83, 67, 100);
INSERT INTO `marioKart`.`Personagem` (`id`, `nome`, `velocidade`, `aceleracao`, `peso`, `manobra`, `tracao`, `turbo`) VALUES (6, 'Rei Bowser', 90, 80, 100, 50, 61, 92);
INSERT INTO `marioKart`.`Personagem` (`id`, `nome`, `velocidade`, `aceleracao`, `peso`, `manobra`, `tracao`, `turbo`) VALUES (7, 'Donkey Kong', 74, 91, 90, 60, 59, 96);

COMMIT;

